### ISSUE TITLE
can you make a vencord version 

### ISSUE THREAD

**Issue by Cxsmo-ai** [Tharki-God/RepluggedPlugins#1]
can you make a vencord version

**Comment by yofukashino** [comment]
No

**Comment by Cxsmo-ai** [comment]
No why because vencord is better then replugged because replugged has no good plugins you know what would be a good plugin for vencord is a easy custom plugin install plugin that adds adding plugins without have to reinstall vencord you add the plugin once then you won't need to reinstall vencord ever again to get not included plugins and also discord bypass plugin for vencord would be cool

**Comment by yofukashino** [comment]
> No why because vencord is better then replugged because replugged has no good plugins you know what would be a good plugin for vencord is a easy custom plugin install plugin that adds adding plugins without have to reinstall vencord you add the plugin once then you won't need to reinstall vencord ever again to get not included plugins and also discord bypass plugin for vencord would be cool

Ven wouldn't approve my plugins so no

**Comment by Cxsmo-ai** [comment]
That doesn't matter you can have third party plugins that you add to the manually compiled version like philhk does and his vencord fork even has updates and stuff that add all the vencord main updates and his own for his plugins

**Comment by yofukashino** [comment]
Still I don't wanna maintain plugins for something I don't use but my code is free to copy. Port it over or pay someone to make it lol

**Comment by Cxsmo-ai** [comment]
Why but replugged is bad because most of it's plugins are not that good and vencord is the most stable client mod when discord breaks bd and stuff vencord has a higher chance working and also vencord is fine with plugins as long as they don't use third party apis and stuff and stick to the vencord apis and stuff

**Comment by yofukashino** [comment]
Whatever I ain't good with plaintextpatch and that's what it uses

**Comment by yofukashino** [comment]
Replugged >>> vencord

I don't want any more discussion on it

**Comment by Kumicoo** [comment]
> Replugged >>> vencord
> 
> I don't want any more discussion on it

Wrong statement + ego problem + crybaby + god complex

Replugged is absolute ass, and cannot even be used right now because it keeps crashing for everyone.

Keep trying to defend a modded discord version that not even the devs give a shit about to fix for new users.

KEKW

**Comment by Cxsmo-ai** [comment]
at least a bd version of discord bypass plugin because then it might be able to be used with bd compatibility layer vencord plugin

**Comment by yofukashino** [comment]
> > Replugged >>> vencord
> > I don't want any more discussion on it
> 
> Wrong statement + ego problem + crybaby + god complex
> 
> Replugged is absolute ass, and cannot even be used right now because it keeps crashing for everyone.
> 
> Keep trying to defend a modded discord version that not even the devs give a shit about to fix for new users.
> 
> KEKW

human

**Comment by yofukashino** [comment]
> at least a bd version of discord bypass plugin because then it might be able to be used with bd compatibility layer vencord plugin

there is a broken version, get it fixed maybe coz idk I don't wanna work with bd

**Comment by Cxsmo-ai** [comment]
but how many people care about replugged after vencord became a thing basically no one so its better to code for a used platform then a dead one which could be bd or vencord even shelter is more used then replugged

**Comment by yofukashino** [comment]
> but how many people care about replugged after vencord became a thing basically no one so its better to code for a used platform then a dead one which could be bd or vencord even shelter is more used then replugged

I can't use Vencord due to a lack of monkey patching and external addon support. even if I make a version for Vencord on request, I really wouldn't manage it. 
yes, not a lot of people use it, but the lag isn't as bad as bd and it's more versatile than Vencord.  which is what I desire~
