### ISSUE TITLE
Hi! could you port bunny lib and your better discord plugins to replugged, I would love to have them back

### ISSUE THREAD

**Issue by Awooochy** [Tharki-God/RepluggedPlugins#2]
uwu

**Comment by yofukashino** [comment]
bunny lib no. individual plugins yes uwu

**Comment by AceLikesGhosts** [comment]
bunny lib best lib

**Comment by yofukashino** [comment]
- lol

**Comment by Acrivec** [comment]
> bunny lib no. individual plugins yes uwu

so basically I should remove all plugins that require bunnylib now?

**Comment by Awooochy** [comment]
or atleast update bunny lib plz

**Comment by yofukashino** [comment]
why? no?

**Comment by Awooochy** [comment]
I still use better discord sadly, if you're free you think you could do a patch plz?

**Comment by Awooochy** [comment]
if I knew js I would do it myself, sadly I only know c#
